/**
 * Reads docs/ and generates the three build artefacts the site needs:
 *
 *   lib/docs/manifest.generated.ts  nav tree, titles, headings (no runtime fs)
 *   lib/docs/registry.generated.ts  route -> () => import('@/docs/…')
 *   public/search-index.json        client-side search corpus
 *
 * Doing the parsing here rather than in a server component means no `fs` at
 * request time, which keeps `output: 'export'` viable, and gives the bundler a
 * statically analysable import map instead of a template-literal dynamic
 * import (which Turbopack resolves far less predictably).
 *
 * Runs in `prebuild` and `dev`, so it cannot drift from the content.
 */
import fs from 'node:fs';
import matter from 'gray-matter';

import {
  DOCS_DIR,
  annotateFences,
  fileToRoute,
  headingSlugs,
  stripInlineMarkdown,
  walkDocs,
} from './lib/content-utils.mjs';

const files = walkDocs(DOCS_DIR, ['.mdx']);
if (!files.length) {
  console.error('No .mdx files found in docs/.');
  process.exit(1);
}

const sectionsSource = fs.readFileSync('lib/docs/sections.ts', 'utf8');
const sectionsJson = JSON.parse(
  sectionsSource.slice(
    sectionsSource.indexOf('DocSection[] = ') + 'DocSection[] = '.length,
    sectionsSource.lastIndexOf('];') + 1,
  ),
);

// ---------------------------------------------------------------------------
// Parse every page
// ---------------------------------------------------------------------------

/**
 * Reading time at 200 words per minute, the usual prose rate.
 *
 * Table rows and headings are counted too — they are what a reader actually
 * scans on these pages — but fenced code is skipped, since nobody reads a CSS
 * snippet at prose speed.
 */
function readingMinutes(body) {
  let words = 0;
  for (const { line, inFence } of annotateFences(body)) {
    if (inFence) continue;
    if (/^\s*<\/?[A-Z]/.test(line)) continue; // <Callout> / </Callout>
    words += (stripInlineMarkdown(line.replace(/[|#>*-]/g, ' ')).match(/\S+/g) || [])
      .length;
  }
  return Math.max(1, Math.round(words / 200));
}

const pages = files.map((file) => {
  const raw = fs.readFileSync(file, 'utf8');
  const { data, content } = matter(raw);
  const route = fileToRoute(file);
  const segments = route === '/' ? [] : route.slice(1).split('/');

  return {
    route,
    slug: segments,
    file,
    title: data.title ?? '',
    description: data.description ?? '',
    order: data.order ?? 999,
    sidebarLabel: data.sidebarLabel ?? data.title ?? '',
    sectionSlug: segments.length > 1 ? segments[0] : null,
    headings: headingSlugs(content).filter((h) => h.depth >= 2 && h.depth <= 3),
    readingMinutes: readingMinutes(content),
    body: content,
  };
});

// ---------------------------------------------------------------------------
// Nav tree — top-level pages first, then the labelled section groups
// ---------------------------------------------------------------------------

const topLevel = pages
  .filter((p) => p.sectionSlug === null)
  .sort((a, b) => a.order - b.order);

const sections = sectionsJson
  .map((section) => ({
    ...section,
    route: `/${section.slug}`,
    pages: pages
      .filter((p) => p.sectionSlug === section.slug)
      .sort((a, b) => a.order - b.order),
  }))
  .sort((a, b) => a.order - b.order);

const missing = sections.filter((s) => !s.pages.length);
if (missing.length) {
  throw new Error(`sections with no pages: ${missing.map((s) => s.slug).join(', ')}`);
}

const orphans = pages.filter(
  (p) => p.sectionSlug && !sections.some((s) => s.slug === p.sectionSlug),
);
if (orphans.length) {
  throw new Error(
    `pages in a folder with no section entry: ${orphans.map((p) => p.route).join(', ')}`,
  );
}

// Flat reading order, for prev/next links at the foot of each page.
const readingOrder = [
  ...topLevel.map((p) => p.route),
  ...sections.flatMap((s) => [s.route, ...s.pages.map((p) => p.route)]),
];

// ---------------------------------------------------------------------------
// manifest.generated.ts
// ---------------------------------------------------------------------------

const slim = (p) => ({
  route: p.route,
  slug: p.slug,
  title: p.title,
  description: p.description,
  order: p.order,
  sidebarLabel: p.sidebarLabel,
  sectionSlug: p.sectionSlug,
  headings: p.headings,
  readingMinutes: p.readingMinutes,
});

const manifest = {
  pages: pages.map(slim),
  topLevel: topLevel.map((p) => p.route),
  sections: sections.map((s) => ({
    slug: s.slug,
    label: s.label,
    order: s.order,
    description: s.description,
    route: s.route,
    pages: s.pages.map((p) => p.route),
  })),
  readingOrder,
};

fs.mkdirSync('lib/docs', { recursive: true });
fs.writeFileSync(
  'lib/docs/manifest.generated.ts',
  `// GENERATED by scripts/sync-content.mjs — do not edit.
// Regenerate with \`pnpm content:sync\`.
import type { DocManifest } from './types';

export const manifest: DocManifest = ${JSON.stringify(manifest, null, 2)} as const;
`,
);

// ---------------------------------------------------------------------------
// registry.generated.ts
// ---------------------------------------------------------------------------

const entries = pages
  .map((p) => `  ${JSON.stringify(p.route)}: () => import('@/${p.file}'),`)
  .join('\n');

fs.writeFileSync(
  'lib/docs/registry.generated.ts',
  `// GENERATED by scripts/sync-content.mjs — do not edit.
// Explicit import thunks rather than a template-literal dynamic import, so the
// bundler can statically resolve every page.
import type { MDXModule } from './types';

export const registry: Record<string, () => Promise<MDXModule>> = {
${entries}
};
`,
);

// ---------------------------------------------------------------------------
// public/search-index.json
// ---------------------------------------------------------------------------

/** Reduce an MDX body to plain searchable prose. */
function toPlainText(body) {
  const lines = [];
  for (const { line, inFence } of annotateFences(body)) {
    if (inFence) continue;
    let text = line;
    if (/^\s*<\/?[A-Z]/.test(text)) continue; // <Callout> / </Callout>
    if (/^\s*\|\s*-+/.test(text)) continue; // table rules
    text = text.replace(/^#{1,6}\s+/, '').replace(/^\s*[-*+]\s+/, '');
    text = text.replace(/\|/g, ' ');
    lines.push(stripInlineMarkdown(text));
  }
  return lines.join(' ').replace(/\s+/g, ' ').trim();
}

/** Split a body into per-heading chunks so hits can deep-link to the section. */
function chunkByHeading(body) {
  const chunks = [];
  let current = { id: null, title: null, lines: [] };
  for (const { line, inFence } of annotateFences(body)) {
    const heading = !inFence && line.match(/^(#{2,3})\s+(.+?)\s*$/);
    if (heading) {
      chunks.push(current);
      const text = stripInlineMarkdown(heading[2]);
      current = { id: null, title: text, lines: [] };
    } else {
      current.lines.push(line);
    }
  }
  chunks.push(current);
  return chunks.filter((c) => c.title || c.lines.some((l) => l.trim()));
}

const searchIndex = {
  pages: pages.map((page) => {
    const slugs = page.headings.map((h) => ({ id: h.id, text: h.text }));
    const chunks = chunkByHeading(page.body).map((chunk) => {
      const match = slugs.find((s) => s.text === chunk.title);
      return {
        i: match?.id ?? '',
        h: chunk.title ?? '',
        x: toPlainText(chunk.lines.join('\n')).slice(0, 700),
      };
    });
    return {
      r: page.route,
      t: page.title,
      d: page.description,
      s: page.sectionSlug
        ? (sections.find((x) => x.slug === page.sectionSlug)?.label ?? '')
        : 'Guide',
      c: chunks.filter((c) => c.h || c.x),
    };
  }),
};

fs.mkdirSync('public', { recursive: true });
fs.writeFileSync('public/search-index.json', JSON.stringify(searchIndex));

const bytes = fs.statSync('public/search-index.json').size;
console.log(
  `content:sync  ${pages.length} pages · ${sections.length} sections · ` +
    `${readingOrder.length} routes · search index ${(bytes / 1024).toFixed(0)} KB`,
);
